# Generated by Django 4.1.6 on 2023-02-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_crop_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weatherrecord',
            name='unique_station_date_constraint',
        ),
        migrations.RemoveConstraint(
            model_name='weatherstationstats',
            name='unique_station_year_constraint',
        ),
        migrations.RenameField(
            model_name='weatherrecord',
            old_name='weather_station_id',
            new_name='weather_station',
        ),
        migrations.RenameField(
            model_name='weatherstationstats',
            old_name='weather_station_id',
            new_name='weather_station',
        ),
        migrations.AddConstraint(
            model_name='weatherrecord',
            constraint=models.UniqueConstraint(fields=('weather_station', 'date'), name='unique_station_date_constraint'),
        ),
        migrations.AddConstraint(
            model_name='weatherstationstats',
            constraint=models.UniqueConstraint(fields=('weather_station', 'year'), name='unique_station_year_constraint'),
        ),
    ]
